autentikasManager/Controllers/PackageController.cs
using DAL.Models;
using DAL.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace autentikasManager.Controllers
{
    [Authorize]
    public class PackageController : Controller
    {
        private PackageRepository packageRepository;

        public PackageController()
        {
            packageRepository = new PackageRepository();
        }

        public string GetPackages()
        {
            var packages = packageRepository.GetActive();
            return new JavaScriptSerializer().Serialize(packages);
        }

        public ActionResult Index()
        {
            var packages = packageRepository.GetAll();
            if (TempData["SuccessMessage"] != null)
                ViewBag.SuccessMessage = TempData["SuccessMessage"];
            return RedirectToAction("Error", "Home", null);
        }

        public ActionResult Edit(int id)
        {
            var package = packageRepository.GetById(id);
            return RedirectToAction("Error", "Home", null);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Package package)
        {
            packageRepository.Edit(package);
            TempData["SuccessMessage"] = "Se editó con éxito el paquete";
            return RedirectToAction("Index");
        }

        public ActionResult Activate(int id)
        {
            var package = packageRepository.GetById(id);
            package.Activate();
            packageRepository.Edit(package);
            TempData["SuccessMessage"] = "Se editó con éxito el paquete";
            return RedirectToAction("Index");
        }
    }
}

autentikasManager/Views/Package/Edit.cshtml
@model DAL.Models.Package
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                @using (Html.BeginForm("Edit", "Package", null, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    @Html.AntiForgeryToken()

                    @Html.HiddenFor(p => p.Description)
                    @Html.HiddenFor(p => p.Id)
                    @Html.HiddenFor(p => p.CookiesQuantity)
                    @Html.HiddenFor(p => p.Active)
                    @Html.HiddenFor(p => p.ActiveDate)
                    @Html.HiddenFor(p => p.DeactiveDate)
                    <small>Nombre</small>
                    <div class="form-group form-group-feedback form-group-feedback-left">
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                        <div class="form-control-feedback">
                            <i class="icon-package text-muted"></i>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">

                            <small>Costo</small>
                            <div class="form-group form-group-feedback form-group-feedback-left">
                                @Html.TextBoxFor(m => m.Cost, new { @class = "form-control", @type = "number", @step = ".01" })
                                <div class="form-control-feedback">
                                    <i class="icon-coin-dollar text-muted"></i>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <small>Precio</small>
                            <div class="form-group form-group-feedback form-group-feedback-left">
                                @Html.TextBoxFor(m => m.Price, new { @class = "form-control", @type = "number", @step = ".01" })
                                <div class="form-control-feedback">
                                    <i class="icon-coin-dollar text-muted"></i>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block">Aceptar<i class="icon-circle-right2 ml-2"></i></button>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="col-md-4"></div>
</div>

autentikasManager/Views/Package/Index.cshtml
@model IList<DAL.Models.Package>

<div class="card">
    <div class="card-body">
        @if (ViewBag.SuccessMessage != null)
        {
            <div class="alert alert-success" role="alert">@ViewBag.SuccessMessage</div>
        }
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>
                        Nombre
                    </th>
                    <th>
                        Descripción
                    </th>
                    <th>
                        Cantidad de galletas
                    </th>
                    @if (User.IsInRole(autentikasManager.Resources.Roles.Admin))
                    {
                        <th>
                            Costo
                        </th>
                    }
                    <th>
                        Precio
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var package in Model)
                {
                    <tr>
                        <td>
                            @if (package.Active)
                            {
                                <i class="icon-alarm-check"></i>
                            }
                            else
                            {
                                <i class="icon-alarm-cancel"></i>
                            }

                            @package.Name
                        </td>
                        <td>
                            @package.Description
                        </td>
                        <td>
                            @package.CookiesQuantity
                        </td>
                        @if (User.IsInRole(autentikasManager.Resources.Roles.Admin))
                        {
                            <td>
                                @string.Format("{0:C}", package.Cost)
                            </td>
                        }
                        <td>
                            @string.Format("{0:C}", package.Price)
                        </td>
                        <td style="text-align:center">
                            @if (User.IsInRole(autentikasManager.Resources.Roles.Admin))
                            {
                                <div class="list-icons">
                                    <div class="dropdown">
                                        <a href="#" class="list-icons-item dropdown-toggle caret-0" data-toggle="dropdown" aria-expanded="false"><i class="icon-menu7"></i></a>
                                        <div class="dropdown-menu dropdown-menu-right" x-placement="bottom-end" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-164px, 19px, 0px);">
                                            <a href="/Package/Edit/@package.Id" class="dropdown-item"><i class="icon-pencil"></i> Editar</a>
                                            @if (package.Active)
                                            {
                                                <a href="/Package/Activate/@package.Id" class="dropdown-item"><i class="icon-warning"></i> Desactivar</a>
                                            }
                                            else
                                            {
                                                <a href="/Package/Activate/@package.Id" class="dropdown-item"><i class="icon-warning"></i> Activar</a>
                                            }

                                        </div>
                                    </div>
                                </div>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>